export const ARAB_COUNTRIES = [
  { value: 'الأردن', label: 'الأردن' },
  { value: 'السعودية', label: 'السعودية' },
  { value: 'مصر', label: 'مصر' },
  { value: 'فلسطين', label: 'فلسطين' },
  { value: 'الكويت', label: 'الكويت' },
  { value: 'الإمارات', label: 'الإمارات' },
  { value: 'البحرين', label: 'البحرين' },
  { value: 'قطر', label: 'قطر' },
  { value: 'سلطنة عُمان', label: 'سلطنة عُمان' },
  { value: 'العراق', label: 'العراق' },
  { value: 'سوريا', label: 'سوريا' },
  { value: 'لبنان', label: 'لبنان' },
  { value: 'اليمن', label: 'اليمن' },
  { value: 'ليبيا', label: 'ليبيا' },
  { value: 'تونس', label: 'تونس' },
  { value: 'الجزائر', label: 'الجزائر' },
  { value: 'المغرب', label: 'المغرب' },
  { value: 'موريتانيا', label: 'موريتانيا' },
  { value: 'السودان', label: 'السودان' },
] as const;
